### ISSUE TITLE
Understanding & Using Issues for collaboration After the Workshop

### ISSUE THREAD

**Issue by edvalency** [mowblox/team1-robust#1]

**Comment by mickeymond** [comment]
@edvalency Did you already know how to use GitHub Issues or did you learn how to  use it from the Video we shared?

**Comment by edvalency** [comment]
I learned it from the video.

**Comment by mickeymond** [comment]
> I learned it from the video.

Awesome.
Then close this issue and let me see if you can.

**Comment by edvalency** [comment]
Ok
